### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by NermalWazza** [Azure-Samples/msdocs-app-service-sqldb-dotnetcore#35]
Following the tutorial build fails - Node.js version

[build]
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by cephalin** [comment]
old issue.
